# -*- coding: utf-8 -*-
"""HTMLExercise_[201721070]

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q-jwNSmmZH4nxo4riSx5zNLUf-IO9lmC
"""



"""# HTML
- 한글처리를 위한 메타태그. lang"ko/kr", charest="utf-8"
- 해딩태그는 뉴라인이 없어서 뉴라인으로 들어감.
- unordered list '<ul>'
- 언오더드는 항목의 순서가 안정해져있음.
- ol ordered list 번호가 매겨짐

img태그. 주소는 상대주소로 찾아감. 현재 위치에서 시작.
- p태그 단락. 문단.
- id="~" 요소들에 고유한 id 1개만 존재

table태그
- thead(테이블헤드) 태그 최상단 라인 th로 나눔
- tbody(테이블바디) tr(table row)에 td로 요소 만듬

- border 겉 라인. style요소로 아름답게
video태그
- 비디오 태그안에 source태그로 영상 주소 잡아줘야함. 근데 비디오의 첫번째 프레임만 나옴.
- 비디오 태그에 오토플레이와 컨트롤즈를 넣어서 시작버튼 넣을 수 있음.
- 유튭 영상은 소스코드 복사로 사용가능

iframe은 자기 html에 외부 소스를 가져올때. 아이프레임은 독립적인 공간임.

다른 사이트를 보려면 f12 눌러서 개발자 도구 고고! 
"""